# Generated by Django 4.2.6 on 2024-03-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DateBook', '0003_alter_datebook_medicine'),
        ('Sale', '0002_alter_sale_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DateBook.datebook'),
        ),
    ]
