# Generated by Django 4.2.6 on 2024-03-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_useraccount_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='lastnames',
            new_name='lastNames',
        ),
    ]
