# Generated by Django 5.0.3 on 2024-03-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_lastnames_useraccount_lastnames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='lastNames',
            new_name='lastnames',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
