# Generated by Django 5.0.3 on 2024-03-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_rename_lastnames_useraccount_lastnames_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='lastnames',
            new_name='lastNames',
        ),
    ]
