# Generated by Django 5.0.3 on 2024-03-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_rename_lastnames_useraccount_lastnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
