# Generated by Django 4.2.6 on 2024-03-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePatient', models.CharField(max_length=30)),
                ('lastNames', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('disease', models.CharField(max_length=30)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine', to='Medicine.medicine')),
            ],
        ),
    ]
