# Generated by Django 4.2.6 on 2024-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMedicine', models.CharField(max_length=30, unique=True)),
                ('group', models.CharField(blank=True, default='', max_length=30)),
                ('exist', models.IntegerField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=0)),
                ('state', models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado'), ('Déficit', 'Déficit'), ('Congelado', 'Congelado')], default='Disponible', max_length=15)),
            ],
        ),
    ]
