# Generated by Django 4.2.6 on 2024-03-23 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(default=0, null=True)),
                ('expDate', models.DateField(default=django.utils.timezone.now)),
                ('amountBatch', models.IntegerField(default=0)),
                ('remainingAmount', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medicine.medicine')),
            ],
        ),
    ]
